spring.application.name=bussin-api

server.port=${PORT:8081}

spring.config.import=optional:file:./secrets/database.properties,optional:classpath:secrets/ai-integration.properties

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=false
